version: "3.5"
services:
  centos7redisphp73:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        image: php-igbinary-7.3

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
