version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.0

workflows:
  igbinarybuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7redis
          build_service: centos7redis
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8redis
          build_service: centos8redis
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7redisphp73
          build_file: docker-compose.php73.yml
          build_service: centos7redisphp73
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8redisphp73
          build_file: docker-compose.php73.yml
          build_service: centos8redisphp73
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7redisphp80
          build_file: docker-compose.php80.yml
          build_service: centos7redisphp80
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8redisphp80
          build_file: docker-compose.php80.yml
          build_service: centos8redisphp80
          bintray_uploader: centos8bintray